# Generated by Django 4.1.6 on 2023-02-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chat_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
